### ISSUE TITLE
Access Denied when trying to auth

### ISSUE THREAD

**Issue by derekantrican** [marcomow/babel-apps-script#1]
Clicked the link in the readme, logged in with Google and got this error:

![image](https://user-images.githubusercontent.com/1558019/102641288-afd22880-4110-11eb-8e95-953c725f717b.png)

**Comment by marcomow** [comment]
That's what I'm referring to in the readme "At the moment the app is not released to general public, and you have to contact me personally to add you to the app. I'm not planning to release (verify) the webapp as I really hope it is just an emergency tool and that soon there won't be the need of it."

Write me an email from the Google account you want to activate and I'll add you to the users' list. You can write to the address in the screenshot
